### ISSUE TITLE
error when running MBAR

### ISSUE THREAD

**Issue by maryam-amin** [alchemistry/alchemlyb#177]
I'm analyzing free energy calculations (Gromacs-based) using alchemlyb. The analysis fails due to the following error:
Traceback (most recent call last):
  File "/home/home/miniconda3/lib/python3.8/site-packages/alchemlyb/alchemical-calc.py", line 21, in <module>
    mbar=MBAR().fit(u_nk)
  File "/home/home/miniconda3/lib/python3.8/site-packages/alchemlyb/estimators/mbar_.py", line 93, in fit
    out = self._mbar.getFreeEnergyDifferences(return_theta=True)
  File "/home/home/miniconda3/lib/python3.8/site-packages/pymbar/mbar.py", line 541, in getFreeEnergyDifferences
    Theta_ij = self._computeAsymptoticCovarianceMatrix(
  File "/home/home/miniconda3/lib/python3.8/site-packages/pymbar/mbar.py", line 1679, in _computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/home/home/miniconda3/lib/python3.8/site-packages/pymbar/utils.py", line 358, in check_w_normalized
    raise ParameterError(
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 1.252731. 30 other columns have similar problems
Can anyone help me and instruct me on what should I do?

**Comment by xiki-tempula** [comment]
Would you mind try 
`from alchemlyb.estimators import AutoMBAR as MBAR`? and run normally.

**Comment by xiki-tempula** [comment]
Would mind check if AutoMBAR is in alchemlyb/src/alchemlyb/estimators/mbar_.py (https://github.com/alchemistry/alchemlyb/blob/a1c0b09dc0ccd98d82e00d3f7b1eb8d5ef3ddef8/src/alchemlyb/estimators/mbar_.py#L140)?

If it not there, you might need to pull the latest version from Github.

**Comment by maryam-amin** [comment]
Thanks, my problem was solved with your instruction.

**Comment by xiki-tempula** [comment]
Good.
